REF: "/mnt/projects/rpd/genomes/gatk-bundle/2.8/b37/human_g1k_v37_decoy.fasta"
SAM: "/mnt/software/stow/samtools-1.7/bin/"
BCF: "/mnt/projects/kayaan/computational_genomics/tools/bcftools-1.7/"
BNPY: "/mnt/projects/kayaan/computational_genomics/tools/bnpy-dev"
UTILS: "/mnt/projects/kayaan/computational_genomics/tools/hatchet/utils/"
HATCHET: "/mnt/projects/kayaan/computational_genomics/tools/hatchet//bin/HATCHet.py"
SOLVER: "/mnt/projects/kayaan/computational_genomics/tools/hatchet/build/solve"


Patients:
    F001:
        normal: "/mnt/projects/yangh/tcga/liver_tcr/WHT637-WHT699.batch14.20190426/after_mapping/data/WHT637.bwamem.dedup.bam"
        tumors: /mnt/projects/yangh/tcga/liver_tcr/WHT637-WHT699.batch14.20190426/after_mapping/data/WHT638.bwamem.dedup.bam /mnt/projects/yangh/tcga/liver_tcr/WHT637-WHT699.batch14.20190426/after_mapping/data/WHT639.bwamem.dedup.bam
        allnames: "WHT637_N WHT638_MF1T1 WHT639_MF1T2"
